name: WordPress Coding Standards

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
         - name: Show files
           run: ls -a
         - name: Install dependencies
           run: composer install --prefer-dist --no-progress 
         - name: PHPCS check
           uses: chekalsky/phpcs-action@v1
           with:
             phpcs_bin_path: './vendor/bin/phpcs'